### ISSUE TITLE
"Unknown" values shown in Home Assistant (Itho HRU) for HRU ECO 300 device

### ISSUE THREAD

**Issue by mkieboom** [jasperslits/haithowifi#78]
I'm having similar challenge as outlined in issue #74 but even when using either the latest stable release (2.1.0) or the latest beta (2.2.0-b3), the sensors keep showing unknown data. The other Wifi add-ons I have connected to my WPU and Autotemp are working perfectly fine.

Device: Itho HRU ECO 300 (interestingly the home assistant shows it as a HRU ECO **350** device but not sure if that makes a difference).

The wifi addon shows MQTT as connected with base topic configured as ithohru:

<img width="809" alt="Screenshot 2024-12-19 at 10 21 46" src="https://github.com/user-attachments/assets/3de5a2dd-f68d-4d0b-899e-0b0bce514b28" />

And in home assistant:
<img width="1032" alt="Screenshot 2024-12-19 at 10 18 41" src="https://github.com/user-attachments/assets/7d655705-87cc-4544-abe5-8b3ea2c2aea4" />

<img width="1218" alt="Screenshot 2024-12-19 at 10 18 58" src="https://github.com/user-attachments/assets/20c10148-5c69-48c2-880f-34b41b16f72e" />

Looking at whats happening at mqtt level I do see data flowing in:

mosquitto_sub -h 192.168.1.2 -t ithohru/state
20

mqtt mosquitto_sub -h 192.168.1.2 -t ithohru/remotesinfo
{}
{}

docker exec -it mqtt mosquitto_sub -h 192.168.1.2 -t ithohru/lastcmd
{"source":"","command":"","timestamp":0}
{"source":"","command":"","timestamp":0}

mosquitto_sub -h 192.168.1.2 -t ithohru/cmd
<returns nothing>

mosquitto_sub -h 192.168.1.2 -t ithohru/lwt
online

mqtt mosquitto_sub -h 192.168.1.2 -t ithohru/ithostatus
<returns continous flow of json objects every 60 seconds >

for example when having HRU ECO 300 running at full speed:

{"Error number":0,"Status":4,"Measured outside temperature (°C)":12.53,"Measured temperature of mixed outside air (°C)":13.05,"The flow of the inflated air (M3/h)":266.1,"Inlet temperature (°C)":20.23,"Temperature of the extracted air (°C)":20.79,"Temperature of the blown out air of the house (°C)":15.33,"The flow of the blown air (m3/h)":244.7,"Relative fanspeed (%)":100,"Absolute speed of the fan (%)":100,"Hysteresis use in control mode (K)":0,"Timer for how long the house is cooled (hour)":0,"Timer for how long the house is heated (hour)":0,"The mass flow of the air entering the house (kg/h)":328.15,"The mass flow of the air leaving the house (kg/h)":298.26,"Percentage that the bypass valve is open (%)":100,"The desired inlet temperature (°C)":17,"Hysteresis of the frost (K)":0,"Number of steps the frost valve is open (steps)":1400,"Number of hours of too cold air (hour)":0,"Temporary speed reduction (rpm)":0,"Sample timer in frost mode (min)":0,"RPM of the motor (rpm)":2247,"Measured waste temperature heated NTC (°C)":27.4,"Measured blend temperature heated NTC (°C)":25.27,"Desired capacity (m3/h)":0,"Busy doing adjustments (-)":0,"Current consumption of fan (mA)":14802,"Desired current consumption of fan (mA)":0,"Highest measured RH (%)":127.5,"Highest measured CO2 (ppm)":579}

and with HRU ECO 300 running at normal speed:

{"Error number":0,"Status":4,"Measured outside temperature (°C)":12.93,"Measured temperature of mixed outside air (°C)":13.44,"The flow of the inflated air (M3/h)":73.2,"Inlet temperature (°C)":20.48,"Temperature of the extracted air (°C)":20.82,"Temperature of the blown out air of the house (°C)":15.24,"The flow of the blown air (m3/h)":68.8,"Relative fanspeed (%)":0,"Absolute speed of the fan (%)":20.5,"Hysteresis use in control mode (K)":0,"Timer for how long the house is cooled (hour)":0,"Timer for how long the house is heated (hour)":0,"The mass flow of the air entering the house (kg/h)":90.12,"The mass flow of the air leaving the house (kg/h)":83.96,"Percentage that the bypass valve is open (%)":100,"The desired inlet temperature (°C)":17,"Hysteresis of the frost (K)":0,"Number of steps the frost valve is open (steps)":1400,"Number of hours of too cold air (hour)":0,"Temporary speed reduction (rpm)":0,"Sample timer in frost mode (min)":0,"RPM of the motor (rpm)":703,"Measured waste temperature heated NTC (°C)":30.46,"Measured blend temperature heated NTC (°C)":29.29,"Desired capacity (m3/h)":0,"Busy doing adjustments (-)":0,"Current consumption of fan (mA)":1378,"Desired current consumption of fan (mA)":0,"Highest measured RH (%)":127.5,"Highest measured CO2 (ppm)":559}

**Comment by benjamin-dcs** [comment]
The HRU300 is not yet supported. We are working on an update which will include every 'version' of the HRU family, including every sensor that is available for that type. Should be released this year

**Comment by benjamin-dcs** [comment]
FYI: https://github.com/jasperslits/haithowifi/pull/77

**Comment by mkieboom** [comment]
Thanks for the quick response and update!

**Comment by benjamin-dcs** [comment]
Please try v2.2.0-b4. Let us know if/how if works. Any feedback is more than welcome!

**Comment by benjamin-dcs** [comment]
I published another update (v2.2.0-b5) with some extra fixes and code improvements. If possible, please update and provide feedback :)

**Comment by maerten** [comment]
<img width="367" alt="Screenshot 2024-12-24 at 12 25 25" src="https://github.com/user-attachments/assets/681e8ff0-dc4a-456d-93c0-4fb887dbfb3c" />
<img width="1004" alt="Screenshot 2024-12-24 at 12 25 31" src="https://github.com/user-attachments/assets/6a9abfea-ab20-4126-a60c-5d13426edb44" />

```
Logger: homeassistant.config_entries
Source: config_entries.py:640
First occurred: 12:25:18 PM (1 occurrences)
Last logged: 12:25:18 PM

Error setting up entry Itho WiFi Add-on for Non-CVE - HRU ECO for ithodaalderop
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ithodaalderop/__init__.py", line 26, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2278, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1184, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1154, in async_get_platforms
    await self.hass.async_add_import_executor_job(
        self._load_platforms, platform_names
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1097, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1271, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1303, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ithodaalderop/sensor.py", line 13, in <module>
    from .sensors.autotemp import get_autotemp_sensors
  File "/config/custom_components/ithodaalderop/sensors/autotemp.py", line 6, in <module>
    from config.custom_components.ithodaalderop.const import (
    ...<8 lines>...
    )
ModuleNotFoundError: No module named 'config.custom_components'
```

**Comment by benjamin-dcs** [comment]
Please try `v2.2.0-b6`

**Comment by maerten** [comment]
That version works

<img width="661" alt="image" src="https://github.com/user-attachments/assets/ab85db8a-47e3-490f-b2f5-f79c39998ef4" />

<img width="342" alt="image" src="https://github.com/user-attachments/assets/5dd98870-1f7a-44d1-b49b-fe0a6c3465ff" />

I see that more entities are switched off by default. Not sure if that is intentional?

**Comment by benjamin-dcs** [comment]
Yes, that's intentional. The HA integration now provides all available sensors from the WiFi Addon. As we don't think all are worthy for every users, we have disabled those by default. If you feel some should be enabled by default, please say so :p

**Comment by maerten** [comment]
that makes sense. not sure if they should be enabled by default.
I think at least the "Last Command / Last Command Source" are interesting

i have just enabled them all for now, not sure what most of them even are since I cannot find any documentation on it.
but at least i can keep an eye on it :) 

<img width="329" alt="image" src="https://github.com/user-attachments/assets/d5703171-0f57-4a2d-8ffb-3f1af9fb734c" />
<img width="329" alt="image" src="https://github.com/user-attachments/assets/74806069-d545-4d9d-bd6f-0df018bc2c54" />

**Comment by benjamin-dcs** [comment]
The 'documentation' part is also where I'm struggling ;) - For some sensors we kinda have to guess their units or whether they are just binary of actual numerical sensors.

**Comment by mkieboom** [comment]
Hi, I can confirm that with the v2.2.0-b6 release I am able to configure the HRU 300 ECO correctly. Thanks for fixing this, works great! See screenshots:

<img width="345" alt="Screenshot 2024-12-30 at 09 37 34" src="https://github.com/user-attachments/assets/7ef65475-8b2b-4f35-b9ee-666195d609d5" />

<img width="1008" alt="Screenshot 2024-12-30 at 09 37 26" src="https://github.com/user-attachments/assets/c3a2fd43-48f6-4fdf-b068-52bad94de916" />

And a bit beyond the scope of this issue, but managed to now steer the HRU fan speed using below HA automation:

`# Define our dropdown list options
input_select:
  itho_hru_fan_speed:
    name: Itho HRU Fan Speed
    options:
      - auto
      - autonight
      - low
      - medium
      - high
      - timer1
      - timer2
      - timer3
    initial: auto

automation:
  # ITHO HRU Fan Speed - auto
  - alias: Set ITHO HRU Fan Speed to auto

    trigger:
      platform: state
      entity_id: input_select.itho_hru_fan_speed

    actions:
      - action: logbook.log
        metadata: {}
        data:
          name: mkmlogbook_log
          message: "{{ trigger.to_state.state | slugify }}"
          entity_id: input_select.itho_hru_fan_speed

      - service: mqtt.publish
        data:
          topic: ithohru/cmd
          payload: "{\"rfremotecmd\":\"{{ trigger.to_state.state | slugify }}\"}"

`

**Comment by benjamin-dcs** [comment]
Hi! First of all, best wishes for 2025! We just released official version `2.2.0`. In case you installed a `2.2.0-beta` release you will miss quite some sensors after installing the official `2.2.0`. This is due to an extra option we introduced after the last beta. See [`available-entities`](https://github.com/jasperslits/haithowifi?tab=readme-ov-file#available-entities) on how to reconfigure your integration entry and get all the entities back (if you so wish)
